### ISSUE TITLE
requirements.txt not honored in 1.2.0

### ISSUE THREAD

**Issue by alohia** [aws/sagemaker-pytorch-inference-toolkit#28]
Hi,

I have a requirements.txt file in the same directory as my generate.py. When I deploy this model, if I use the container for pytorch 1.3.1, the packages in requirements.txt get installed (expected behavior).
However, when using pytorch 1.2.0, the requirements.txt file is ignored and no specified packages are installed. Where is the requirements.txt file used to install the packages? Can someone point me to that?

Thanks
Akhil

**Comment by laurenyu** [comment]
Sorry for the delay in response.

Unfortunately, requirements.txt support is available only for PyTorch 1.3.1+ with the serving images. Is there a reason you need 1.2.0 specifically?

**Comment by alohia** [comment]
It is also supported in 1.1.0. I need 1.2.0 because pytorch 1.3.1 gives a higher latency for my model. Can you point me to the code section where this part is implemented? I will look into incorporating this.

**Comment by laurenyu** [comment]
you will need to rebuild the Docker image with the updated source in https://github.com/aws/sagemaker-inference-toolkit, which is a dependency of this repository.

alternatively, you could try something like

```python
import sys

sys.check_call([sys.executable, '-m', 'pip', 'install', '-r', 'requirements.txt'])
```

in your inference script.

I've also reached out to the team responsible for building the PyTorch images to see if they would be able to update the 1.2.0 images.

**Comment by awcchungster** [comment]
Hi @alohia, we recently release the PyTorch 1.4.0 containers. Does that work with your inference workflow?
