### ISSUE TITLE
unable to build

### ISSUE THREAD

**Issue by AtsunoriFujita** [aws/sagemaker-pytorch-inference-toolkit#70]
I am unable to build an image with the dockerfile in this repo.
I'm using gpu version and below is the error.
How can I fix the error?

Environment : sagemaker 
And I cloned this repository.

pytorch 1.4.0
`Step 18/27 : COPY mms-entrypoint.py /usr/local/bin/dockerd-entrypoint.py
COPY failed: stat /var/lib/docker/tmp/docker-builder661779586/mms-entrypoint.py: no such file or directory`

pytorch 1.2.0, 1.3.1
`Step 15/26 : RUN curl -o ~/miniconda.sh -O  https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh  && chmod +x ~/miniconda.sh  && ~/miniconda.sh -b -p /opt/conda  && rm ~/miniconda.sh  && /opt/conda/bin/conda update conda  && /opt/conda/bin/conda install -y     python=$PYTHON_VERSION     cython==0.29.12     ipython==7.7.0     mkl-include==2019.4     mkl==2019.4     numpy==1.16.4     scipy==1.3.0     typing==3.6.4  && /opt/conda/bin/conda clean -ya
 ---> Running in 1733b9e3bc06
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
/bin/sh: 1: /opt/conda/bin/conda: not found
The command '/bin/sh -c curl -o ~/miniconda.sh -O  https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh  && chmod +x ~/miniconda.sh  && ~/miniconda.sh -b -p /opt/conda  && rm ~/miniconda.sh  && /opt/conda/bin/conda update conda&& /opt/conda/bin/conda install -y     python=$PYTHON_VERSION     cython==0.29.12     ipython==7.7.0     mkl-include==2019.4     mkl==2019.4     numpy==1.16.4     scipy==1.3.0     typing==3.6.4  && /opt/conda/bin/conda clean -ya' returned a non-zero code: 127`

**Comment by AtsunoriFujita** [comment]
I resolved 1.4.0 error.

`COPY ./docker/build_artifacts/mms-entrypoint.py /usr/local/bin/dockerd-entrypoint.py
COPY ./docker/build_artifacts/config.properties /home/model-server`

1.2.0, 1.3.1 are syntax errors.
You will also need to change your PATH as you did in 1.4.0.

**Comment by laurenyu** [comment]
sorry to hear that you had trouble building the images, but glad to see that you were able to resolve the issue. Indeed, our documentation is rather out of date, but the expected workflow is to copy the files under `docker/build_artifacts` to the location of the Dockerfile you're using to build an image ([example](https://github.com/aws/sagemaker-pytorch-serving-container/blob/master/buildspec.yml#L45)).

**Comment by laurenyu** [comment]
the Dockerfiles (and image building) have been moved to https://github.com/aws/deep-learning-containers
